// Generated by CoffeeScript 1.9.2
(function() {
  var expect, runTests, testdata, verifydata;

  expect = chai.expect;

  testdata = {
    "PersonalDetails.Honorific": "Mr.",
    "PersonalDetails.FirstName": "Steve",
    "PersonalDetails.MiddleName": "Roberto",
    "PersonalDetails.LastName": "McQueen",
    "PersonalDetails.BirthDate.Day": "12",
    "PersonalDetails.BirthDate.Month": "05",
    "PersonalDetails.BirthDate.Year": "1973",
    "ContactDetails.Emails.Email.Address": "steve@mcqueen.com",
    "AddressDetails.HomeAddress.LevelNumber": "",
    "AddressDetails.HomeAddress.UnitNumber": "",
    "AddressDetails.HomeAddress.StreetNumber": "27",
    "AddressDetails.HomeAddress.StreetName": "Oakmont",
    "AddressDetails.HomeAddress.StreetType": "DRIVE",
    "AddressDetails.HomeAddress.Suburb": "Brentwood",
    "AddressDetails.HomeAddress.AdministrativeArea": "California",
    "AddressDetails.HomeAddress.PostalCode": "94513",
    "AddressDetails.HomeAddress.Country": "United States",
    "AddressDetails.HomeAddress.BuildingName": "",
    "AddressDetails.PostalAddress.POBox": "555",
    "AddressDetails.PostalAddress.LevelNumber": "",
    "AddressDetails.PostalAddress.UnitNumber": "",
    "AddressDetails.PostalAddress.StreetNumber": "18",
    "AddressDetails.PostalAddress.StreetName": "Oak",
    "AddressDetails.PostalAddress.StreetType": "STREET",
    "AddressDetails.PostalAddress.Suburb": "Los Angeles",
    "AddressDetails.PostalAddress.AdministrativeArea": "CA",
    "AddressDetails.PostalAddress.PostalCode": "90096",
    "AddressDetails.PostalAddress.Country": "United States",
    "AddressDetails.PostalAddress.BuildingName": "",
    "AddressDetails.BillingAddress.POBox": "",
    "AddressDetails.BillingAddress.LevelNumber": "6",
    "AddressDetails.BillingAddress.UnitNumber": "34",
    "AddressDetails.BillingAddress.StreetNumber": "1419",
    "AddressDetails.BillingAddress.StreetName": "Westwood",
    "AddressDetails.BillingAddress.StreetType": "BOULEVARD",
    "AddressDetails.BillingAddress.Suburb": "Los Angeles",
    "AddressDetails.BillingAddress.AdministrativeArea": "CA",
    "AddressDetails.BillingAddress.PostalCode": "90024",
    "AddressDetails.BillingAddress.Country": "United States",
    "AddressDetails.WorkAddress.POBox": "",
    "AddressDetails.WorkAddress.LevelNumber": "",
    "AddressDetails.WorkAddress.UnitNumber": "12a",
    "AddressDetails.WorkAddress.StreetNumber": "100",
    "AddressDetails.WorkAddress.StreetName": "Universal City",
    "AddressDetails.WorkAddress.StreetType": "PLAZA",
    "AddressDetails.WorkAddress.Suburb": "Universal City",
    "AddressDetails.WorkAddress.AdministrativeArea": "CA",
    "AddressDetails.WorkAddress.PostalCode": "91608",
    "AddressDetails.WorkAddress.Country": "United States"
  };

  verifydata = {
    "https://info.bpiexpressonline.com/bpiprod/eolappli.nsf/CreditCardApplicationForm?OpenForm": {
      "PersonalDetails.Honorific": "input[name='Honorific']",
      "PersonalDetails.FirstName": "input[name='FirstName']",
      "PersonalDetails.MiddleName": "input[name='MiddleName']",
      "PersonalDetails.LastName": "input[name='LastName']",
      "PersonalDetails.BirthDate.Day": "select[name='BirthDD']",
      "PersonalDetails.BirthDate.Month": "select[name='BirthMM']",
      "PersonalDetails.BirthDate.Year": "select[name='BirthYY']",
      "ContactDetails.Emails.Email.Address": "input[name='EmailAdd']",
      "AddressDetails.HomeAddress.LevelNumber": "",
      "AddressDetails.HomeAddress.UnitNumber": "",
      "AddressDetails.HomeAddress.StreetNumber": "27",
      "AddressDetails.HomeAddress.StreetName": "Oakmont",
      "AddressDetails.HomeAddress.StreetType": "DRIVE",
      "AddressDetails.HomeAddress.Suburb": "Brentwood",
      "AddressDetails.HomeAddress.AdministrativeArea": "California",
      "AddressDetails.HomeAddress.PostalCode": "94513",
      "AddressDetails.HomeAddress.Country": "United States",
      "AddressDetails.HomeAddress.BuildingName": "",
      "AddressDetails.PostalAddress.POBox": "555",
      "AddressDetails.PostalAddress.LevelNumber": "",
      "AddressDetails.PostalAddress.UnitNumber": "",
      "AddressDetails.PostalAddress.StreetNumber": "18",
      "AddressDetails.PostalAddress.StreetName": "Oak",
      "AddressDetails.PostalAddress.StreetType": "STREET",
      "AddressDetails.PostalAddress.Suburb": "Los Angeles",
      "AddressDetails.PostalAddress.AdministrativeArea": "CA",
      "AddressDetails.PostalAddress.PostalCode": "90096",
      "AddressDetails.PostalAddress.Country": "United States",
      "AddressDetails.PostalAddress.BuildingName": "",
      "AddressDetails.BillingAddress.POBox": "",
      "AddressDetails.BillingAddress.LevelNumber": "6",
      "AddressDetails.BillingAddress.UnitNumber": "34",
      "AddressDetails.BillingAddress.StreetNumber": "1419",
      "AddressDetails.BillingAddress.StreetName": "Westwood",
      "AddressDetails.BillingAddress.StreetType": "BOULEVARD",
      "AddressDetails.BillingAddress.Suburb": "Los Angeles",
      "AddressDetails.BillingAddress.AdministrativeArea": "CA",
      "AddressDetails.BillingAddress.PostalCode": "90024",
      "AddressDetails.BillingAddress.Country": "United States",
      "AddressDetails.WorkAddress.POBox": "",
      "AddressDetails.WorkAddress.LevelNumber": "",
      "AddressDetails.WorkAddress.UnitNumber": "12a",
      "AddressDetails.WorkAddress.StreetNumber": "100",
      "AddressDetails.WorkAddress.StreetName": "Universal City",
      "AddressDetails.WorkAddress.StreetType": "PLAZA",
      "AddressDetails.WorkAddress.Suburb": "Universal City",
      "AddressDetails.WorkAddress.AdministrativeArea": "CA",
      "AddressDetails.WorkAddress.PostalCode": "91608",
      "AddressDetails.WorkAddress.Country": "United States"
    },
    "http://www.garnier.com.au/register": {
      "PersonalDetails.Honorific": "input[name='Honorific']",
      "PersonalDetails.FirstName": "input[name='FirstName']",
      "PersonalDetails.MiddleName": "input[name='MiddleName']",
      "PersonalDetails.LastName": "input[name='LastName']",
      "PersonalDetails.BirthDate.Day": "select[name='BirthDD']",
      "PersonalDetails.BirthDate.Month": "select[name='BirthMM']",
      "PersonalDetails.BirthDate.Year": "select[name='BirthYY']",
      "ContactDetails.Emails.Email.Address": "input[name='EmailAdd']",
      "AddressDetails.HomeAddress.LevelNumber": "",
      "AddressDetails.HomeAddress.UnitNumber": "",
      "AddressDetails.HomeAddress.StreetNumber": "",
      "AddressDetails.HomeAddress.StreetName": "",
      "AddressDetails.HomeAddress.StreetType": "",
      "AddressDetails.HomeAddress.Suburb": "",
      "AddressDetails.HomeAddress.AdministrativeArea": "",
      "AddressDetails.HomeAddress.PostalCode": "",
      "AddressDetails.HomeAddress.Country": "",
      "AddressDetails.HomeAddress.BuildingName": ""
    },
    "https://www.qantas.com.au/fflyer/do/dyns/joinff": {
      "PersonalDetails.Honorific": "input[name='Honorific']",
      "PersonalDetails.FirstName": "input[name='customerNameGivenName']",
      "PersonalDetails.MiddleName": "input[name='customerNameMiddleInitial']",
      "PersonalDetails.LastName": "input[name='customerNameSurname']",
      "PersonalDetails.BirthDate.Day": "select[name='dobDay']",
      "PersonalDetails.BirthDate.Month": "select[name='dobMonth']",
      "PersonalDetails.BirthDate.Year": "select[name='dobYear']",
      "ContactDetails.Emails.Email.Address": "input[name='emailAddressAddress']",
      "AddressDetails.HomeAddress.Line1": "input[name='postalAddressLine1']",
      "AddressDetails.HomeAddress.Suburb": "nput[name='postalAddressCity']",
      "AddressDetails.HomeAddress.AdministrativeArea": "select[name='postalAddressState']",
      "AddressDetails.HomeAddress.PostalCode": "input[name='postalAddressPostCode']",
      "AddressDetails.HomeAddress.Country": "select[name='homePhoneNumberCountry']",
      "AddressDetails.HomeAddress.BuildingName": ""
    }
  };

  runTests = function(doc, verify, data) {
    doc.fillWith(data);
    describe("First Name", function() {
      return it("should be populated by the test data", function() {
        return expect(doc.find(verify["PersonalDetails.FirstName"]).val()).to.equal(data["PersonalDetails.FirstName"]);
      });
    });
    describe("Middle Name", function() {
      return it("should be populated by the test data", function() {
        return expect(doc.find(verify["PersonalDetails.MiddleName"]).val()).to.equal(data["PersonalDetails.MiddleName"]);
      });
    });
    describe("Surname", function() {
      return it("should be populated by the test data", function() {
        return expect(doc.find(verify["PersonalDetails.LastName"]).val()).to.equal(data["PersonalDetails.LastName"]);
      });
    });
    describe("Birthdate Day", function() {
      return it("should be populated by the test data", function() {
        return expect(doc.find(verify["PersonalDetails.BirthDate.Day"]).val()).to.equal(data["PersonalDetails.BirthDate.Day"]);
      });
    });
    describe("Birthdate Month", function() {
      return it("should be populated by the test data", function() {
        return expect(doc.find(verify["PersonalDetails.BirthDate.Month"]).val()).to.equal(data["PersonalDetails.BirthDate.Month"]);
      });
    });
    describe("Birthdate Year", function() {
      return it("should be populated by the test data", function() {
        return expect(doc.find(verify["PersonalDetails.BirthDate.Year"]).val()).to.equal(data["PersonalDetails.BirthDate.Year"]);
      });
    });
    describe("Contact Email", function() {
      return it("should be populated by the test data", function() {
        return expect(doc.find(verify["ContactDetails.Emails.Email.Address"]).val()).to.equal(data["ContactDetails.Emails.Email.Address"]);
      });
    });
    return mocha.run();
  };

  $(document).ready(function() {
    var testformurl;
    testformurl = typeof test_staging === "undefined" ? window.location.href : "https://info.bpiexpressonline.com/bpiprod/eolappli.nsf/CreditCardApplicationForm?OpenForm";
    return $('<button />').prependTo('body').text("Run tests").click(function() {
      return runTests($("body"), verifydata[testformurl], testdata);
    });
  });

}).call(this);
